name: linux64 debug

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install linux64 dependencies
        run: sudo ./bldsys/install_ubuntu_dependencies.sh
      - name: build linux64 debug
        run: ./bldsys/build.sh debug


